name: Build 

on: 
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # setup build tools: ninja, conan
      - name: Setup Ninja
        run: sudo apt-get install ninja-build
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Check tools
        run: conan --version && ninja --version && echo $PATH

      # build phase
      - name: Build
        run: | 
          python build.py 

      
