name: Build 

on: 
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  CONAN_PRINT_RUN_COMMANDS: 1

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        build_params: [""] 
        include:
          # includes cross-compiling combinations for android
          - os: ubuntu-latest
            build_params: "-pr $(pwd)/buildtools/conan-profiles/android-armv7"
          - os: ubuntu-latest
            build_params: "-pr $(pwd)/buildtools/conan-profiles/android-armv8"
          - os: ubuntu-latest
            build_params: "-pr $(pwd)/buildtools/conan-profiles/android-x86_64"
          # includes cross-compiling combinations for ios
          - os: macos-latest
            build_params: "-pr $(pwd)/buildtools/conan-profiles/ios-armv7"
          - os: macos-latest
            build_params: "-pr $(pwd)/buildtools/conan-profiles/ios-armv8"

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      # setup build tools: ninja, conan, yasm
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: turtlebrowser/get-conan@main
      - name: Check tools
        run: conan --version && ninja --version && echo $PATH

      # Install platform specified requirements
      - name: Install yasm on Ubuntu runner
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get install yasm
      - name: Install yasm on macOSX runner
        if: startsWith(matrix.os, 'macos')
        run: brew install yasm

      # build phase
      - name: Build
        run: | 
          python3 build.py ${{ matrix.build_params }}

      # view built conan packages
      - name: View built packages
        run : |
          conan search "*"
