name: Build 

on: 
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:
    branches:
      - main

env:
  CONAN_PRINT_RUN_COMMANDS: 1
  CONAN_DEFAULT_PROFILE_PATH: ${GITHUB_WORKSPACE}/buildtools/conan-profiles

jobs:
  build:
    strategy:
      matrix:
        build_params: 
          - ""  # default gcc
          # - "-s compiler=clang -s compiler.version=12"
          - "-pr android-armv7"
          - "-pr android-armv8"
          - "-pr android-x86_64"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      # setup build tools: ninja, conan
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build requirements
        run: sudo apt-get install yasm
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Check tools
        run: conan --version && ninja --version && echo $PATH

      # build phase
      - name: Build
        run: | 
          python3 build.py ${{ matrix.build_params }}

      # view built conan packages
      - name: View built packages
        run : |
          conan search "*"

  build-on-mac:
    strategy:
      matrix:
        build_params: 
          - ""  # host macos
          - "-pr ios-armv7"
          - "-pr ios-armv8"
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: 'true'

      # setup build tools: ninja, conan
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Setup build requirements
        run: brew install yasm
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
      - name: Check tools
        run: conan --version && ninja --version && echo $PATH

      # build phase
      - name: Build
        run: | 
          python3 build.py ${{ matrix.build_params }}

      # view built conan packages
      - name: View built packages
        run : |
          conan search "*"